<?php

declare(strict_types=1);

namespace Webconsulting\Abilities\Projection\Mcp;

use Hn\McpServer\MCP\Tool\ToolInterface;
use Mcp\Types\CallToolResult;
use Mcp\Types\TextContent;
use Webconsulting\Abilities\Domain\AbilityDefinition;
use Webconsulting\Abilities\Domain\ExecutionContext;
use Webconsulting\Abilities\Execution\AbilityExecutor;
use Webconsulting\Abilities\Registry\AbilityInterface;

/**
 * MCP projection of one ability. Instances are generated by the compiler
 * pass in Configuration/Services.php — one per registered ability that is
 * exposed to the "mcp" surface — and tagged "mcp.tool" so hn/typo3-mcp-server
 * picks them up like native tools. The MCP tool list IS the registry.
 *
 * This class is only wired when hn/typo3-mcp-server is installed; it must
 * not be referenced otherwise.
 */
final class AbilityMcpTool implements ToolInterface
{
    private ?AbilityDefinition $definition = null;

    public function __construct(
        private readonly AbilityInterface $ability,
        private readonly AbilityExecutor $executor,
    ) {
    }

    public function getName(): string
    {
        return $this->getDefinition()->mcpToolName();
    }

    /**
     * @return array<string, mixed>
     */
    public function getSchema(): array
    {
        $definition = $this->getDefinition();
        $inputSchema = $this->ability->getInputSchema();
        if ($inputSchema === []) {
            $inputSchema = ['type' => 'object', 'properties' => new \stdClass()];
        }

        return [
            'description' => sprintf('%s — %s', $definition->title, $definition->description),
            'inputSchema' => $inputSchema,
            'annotations' => [
                'title' => $definition->title,
                'readOnlyHint' => $definition->isReadOnly(),
                'destructiveHint' => $definition->destructive,
                'idempotentHint' => $definition->idempotent,
                'openWorldHint' => $this->touchesNetwork($definition),
            ],
        ];
    }

    /**
     * @param array<string, mixed> $params
     */
    public function execute(array $params): CallToolResult
    {
        $result = $this->executor->execute($this->ability, $params, ExecutionContext::mcp());

        $json = json_encode($result->toArray(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($json === false) {
            return new CallToolResult(
                [new TextContent('Ability result could not be encoded as JSON: ' . json_last_error_msg())],
                true,
            );
        }

        return new CallToolResult([new TextContent($json)], !$result->ok);
    }

    private function getDefinition(): AbilityDefinition
    {
        return $this->definition ??= AbilityDefinition::fromInstance($this->ability);
    }

    private function touchesNetwork(AbilityDefinition $definition): bool
    {
        foreach ($definition->sideEffects as $sideEffect) {
            if (str_starts_with($sideEffect, 'network:')) {
                return true;
            }
        }

        return false;
    }
}
